API_HOST_URL: 'http://digitalkora.indus.edvay.com' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'DigitalKora'
PLATFORM_NAME: 'DigitalKora'
PLATFORM_DESTINATION_NAME: 'DigitalKora'
FEEDBACK_EMAIL_ADDRESS: 'support@edvay.com'
DISCUSSIONS_ENABLED: True
NEW_LOGISTRATION_ENABLED : False
